#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: cmake
# autospec version: v18
# autospec commit: eaa4f711da30
#
Name     : mold
Version  : 2.33.0
Release  : 3
URL      : https://github.com/rui314/mold/archive/v2.33.0/mold-2.33.0.tar.gz
Source0  : https://github.com/rui314/mold/archive/v2.33.0/mold-2.33.0.tar.gz
Summary  : @PROJECT_DESCRIPTION@
Group    : Development/Tools
License  : Apache-2.0 BSD-2-Clause BSD-3-Clause BSL-1.0 GPL-2.0 MIT Zlib
Requires: mold-bin = %{version}-%{release}
Requires: mold-lib = %{version}-%{release}
Requires: mold-libexec = %{version}-%{release}
Requires: mold-license = %{version}-%{release}
Requires: mold-man = %{version}-%{release}
BuildRequires : buildreq-cmake
BuildRequires : doxygen
BuildRequires : glibc-dev
BuildRequires : libX11-dev libICE-dev libSM-dev libXau-dev libXcomposite-dev libXcursor-dev libXdamage-dev libXdmcp-dev libXext-dev libXfixes-dev libXft-dev libXi-dev libXinerama-dev libXi-dev libXmu-dev libXpm-dev libXrandr-dev libXrender-dev libXres-dev libXScrnSaver-dev libXt-dev libXtst-dev libXv-dev libXxf86vm-dev
BuildRequires : mesa-dev
BuildRequires : pkg-config
BuildRequires : python3
BuildRequires : zlib-dev
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
ZLIB DATA COMPRESSION LIBRARY
zlib 1.3.1 is a general purpose data compression library.  All the code is
thread safe.  The data format used by the zlib library is described by RFCs
(Request for Comments) 1950 to 1952 in the files
http://tools.ietf.org/html/rfc1950 (zlib format), rfc1951 (deflate format) and
rfc1952 (gzip format).

%package bin
Summary: bin components for the mold package.
Group: Binaries
Requires: mold-libexec = %{version}-%{release}
Requires: mold-license = %{version}-%{release}

%description bin
bin components for the mold package.


%package doc
Summary: doc components for the mold package.
Group: Documentation
Requires: mold-man = %{version}-%{release}

%description doc
doc components for the mold package.


%package lib
Summary: lib components for the mold package.
Group: Libraries
Requires: mold-libexec = %{version}-%{release}
Requires: mold-license = %{version}-%{release}

%description lib
lib components for the mold package.


%package libexec
Summary: libexec components for the mold package.
Group: Default
Requires: mold-license = %{version}-%{release}

%description libexec
libexec components for the mold package.


%package license
Summary: license components for the mold package.
Group: Default

%description license
license components for the mold package.


%package man
Summary: man components for the mold package.
Group: Default

%description man
man components for the mold package.


%prep
%setup -q -n mold-2.33.0
cd %{_builddir}/mold-2.33.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1723145325
mkdir -p clr-build
pushd clr-build
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export GOAMD64=v2
%cmake ..   -G 'Unix Makefiles'
make  %{?_smp_mflags}
popd

%install
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export SOURCE_DATE_EPOCH=1723145325
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/mold
cp %{_builddir}/mold-%{version}/LICENSE %{buildroot}/usr/share/package-licenses/mold/434e8deb747949e7e59f83227e780c1784955acb || :
cp %{_builddir}/mold-%{version}/LICENSE.third-party %{buildroot}/usr/share/package-licenses/mold/fa8a6983305679244b2febc4bfb1f7ce650fc6d6 || :
cp %{_builddir}/mold-%{version}/third-party/blake3/LICENSE %{buildroot}/usr/share/package-licenses/mold/bfc2b026231b7aca6db90de3471e76dbb94e9c24 || :
cp %{_builddir}/mold-%{version}/third-party/mimalloc/LICENSE %{buildroot}/usr/share/package-licenses/mold/4e0d5d15ab4f212c645d939f71c319ba648a8cce || :
cp %{_builddir}/mold-%{version}/third-party/rust-demangle/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/mold/6e5c4711bcae04967d7f5b5e01cf56ae03bebe7a || :
cp %{_builddir}/mold-%{version}/third-party/rust-demangle/LICENSE-MIT %{buildroot}/usr/share/package-licenses/mold/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/mold-%{version}/third-party/tbb/LICENSE.txt %{buildroot}/usr/share/package-licenses/mold/7df059597099bb7dcf25d2a9aedfaf4465f72d8d || :
cp %{_builddir}/mold-%{version}/third-party/xxhash/LICENSE %{buildroot}/usr/share/package-licenses/mold/8f9141a1e770538c5d247d834cb96153541be26b || :
cp %{_builddir}/mold-%{version}/third-party/xxhash/cli/COPYING %{buildroot}/usr/share/package-licenses/mold/4cc77b90af91e615a64ae04893fdffa7939db84c || :
cp %{_builddir}/mold-%{version}/third-party/xxhash/tests/bench/LICENSE %{buildroot}/usr/share/package-licenses/mold/4cc77b90af91e615a64ae04893fdffa7939db84c || :
cp %{_builddir}/mold-%{version}/third-party/xxhash/tests/collisions/LICENSE %{buildroot}/usr/share/package-licenses/mold/4cc77b90af91e615a64ae04893fdffa7939db84c || :
cp %{_builddir}/mold-%{version}/third-party/zlib/LICENSE %{buildroot}/usr/share/package-licenses/mold/233f44af3fb55dcc7fddfef8e77ac627b0008756 || :
cp %{_builddir}/mold-%{version}/third-party/zlib/contrib/dotzlib/LICENSE_1_0.txt %{buildroot}/usr/share/package-licenses/mold/892b34f7865d90a6f949f50d95e49625a10bc7f0 || :
cp %{_builddir}/mold-%{version}/third-party/zstd/COPYING %{buildroot}/usr/share/package-licenses/mold/1d8c93712cbc9117a9e55a7ff86cebd066c8bfd8 || :
cp %{_builddir}/mold-%{version}/third-party/zstd/LICENSE %{buildroot}/usr/share/package-licenses/mold/d5e630eee1d3500039f2e16bed21d0f0cd580994 || :
export GOAMD64=v2
GOAMD64=v2
pushd clr-build
%make_install
popd

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/ld.mold
/usr/bin/mold

%files doc
%defattr(0644,root,root,0755)
/usr/share/doc/mold/*

%files lib
%defattr(-,root,root,-)
/usr/lib64/mold/mold-wrapper.so

%files libexec
%defattr(-,root,root,-)
/usr/libexec/mold/ld

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/mold/1d8c93712cbc9117a9e55a7ff86cebd066c8bfd8
/usr/share/package-licenses/mold/233f44af3fb55dcc7fddfef8e77ac627b0008756
/usr/share/package-licenses/mold/434e8deb747949e7e59f83227e780c1784955acb
/usr/share/package-licenses/mold/4cc77b90af91e615a64ae04893fdffa7939db84c
/usr/share/package-licenses/mold/4e0d5d15ab4f212c645d939f71c319ba648a8cce
/usr/share/package-licenses/mold/6e5c4711bcae04967d7f5b5e01cf56ae03bebe7a
/usr/share/package-licenses/mold/7df059597099bb7dcf25d2a9aedfaf4465f72d8d
/usr/share/package-licenses/mold/892b34f7865d90a6f949f50d95e49625a10bc7f0
/usr/share/package-licenses/mold/8f9141a1e770538c5d247d834cb96153541be26b
/usr/share/package-licenses/mold/bfc2b026231b7aca6db90de3471e76dbb94e9c24
/usr/share/package-licenses/mold/ce3a2603094e799f42ce99c40941544dfcc5c4a5
/usr/share/package-licenses/mold/d5e630eee1d3500039f2e16bed21d0f0cd580994
/usr/share/package-licenses/mold/fa8a6983305679244b2febc4bfb1f7ce650fc6d6

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man1/ld.mold.1
/usr/share/man/man1/mold.1
